version: '3'
services:
  http-shield:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_HOST: 'demo'
      SERVER_PORT: '3000'
      ENDPOINTS_0: '1:/api/heavy1,/api/heavy2'
  demo:
    build: demo-app
    ports:
      - "3000"
